steps:
  # Build the container image from repo root
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-f', 'backend/services/job-initiation-api/Dockerfile',
      '-t', 'gcr.io/$PROJECT_ID/job-initiation-api:$COMMIT_SHA', 
      '.'  # Build from repo root
    ]
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/job-initiation-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'job-initiation-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/job-initiation-api:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID,FIRESTORE_JOBS_COLLECTION=jobs,PUBSUB_CONTENT_RETRIEVAL_TOPIC=content-retrieval'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/job-initiation-api:$COMMIT_SHA'
